[2023-03-16T18:58:06.132+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 0_Employee_Sync_Granular_Steps.save_user_data manual__2023-03-16T18:58:00.693085+00:00 [queued]>
[2023-03-16T18:58:06.138+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 0_Employee_Sync_Granular_Steps.save_user_data manual__2023-03-16T18:58:00.693085+00:00 [queued]>
[2023-03-16T18:58:06.139+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T18:58:06.139+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-16T18:58:06.140+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T18:58:06.147+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): save_user_data> on 2023-03-16 18:58:00.693085+00:00
[2023-03-16T18:58:06.152+0000] {standard_task_runner.py:55} INFO - Started process 46000 to run task
[2023-03-16T18:58:06.156+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '0_Employee_Sync_Granular_Steps', 'save_user_data', 'manual__2023-03-16T18:58:00.693085+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/test_dag_granular.py', '--cfg-path', '/tmp/tmp66vrzv01']
[2023-03-16T18:58:06.159+0000] {standard_task_runner.py:83} INFO - Job 86: Subtask save_user_data
[2023-03-16T18:58:06.206+0000] {task_command.py:376} INFO - Running <TaskInstance: 0_Employee_Sync_Granular_Steps.save_user_data manual__2023-03-16T18:58:00.693085+00:00 [running]> on host 9fe6516b8a01
[2023-03-16T18:58:06.259+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=0_Employee_Sync_Granular_Steps
AIRFLOW_CTX_TASK_ID=save_user_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-16T18:58:00.693085+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-16T18:58:00.693085+00:00
[2023-03-16T18:58:06.273+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-16T18:58:06.282+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=0_Employee_Sync_Granular_Steps, task_id=save_user_data, execution_date=20230316T185800, start_date=20230316T185806, end_date=20230316T185806
[2023-03-16T18:58:06.328+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-03-16T18:58:06.349+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
